### ISSUE TITLE
option can be in optgroup and select elements

### ISSUE THREAD

**Issue by a5e** [ffoodd/a11y.css#123]
In [this test](https://ffoodd.github.io/a11y.css/errors.html#optgroup) options are targeted by a warning because they are not direct childs of a select. We should only make sure that they are childs of a select or childs of an optgroup with a select parent.

I think this is because of this selector `:not(select) > option`

**Comment by ffoodd** [comment]
You're right!

This is done is [the invalid nesting case](https://ffoodd.github.io/a11y.css/warnings.html#invalid-nesting) (a warning).

I will change the selector to be more accurate. Thanks!
