### ISSUE TITLE
Update and themify Sassdoc + Hologram

### ISSUE THREAD

**Issue by ffoodd** [ffoodd/a11y.css#130]
I think we could include Sassdoc in the project's static site, by simply themify it and use a Hologram-like template styled with sseeeedd.

**Comment by HugoGiraudel** [comment]
SassDoc is quite easy to themify by the way. :)

**Comment by ffoodd** [comment]
I briefly read Sassdoc's website and it seems pretty simple, indeed :)
I need to discover Sassdoc but I think it'll be very interesting!

**Comment by ffoodd** [comment]
I'm currently considering this point as a complete redesign of a11y.css' documentation site.

I'll probably do something like [Algolia's documentation site](https://www.algolia.com/doc) or in that kind of thing.

Still drawing!

**Comment by ffoodd** [comment]
Examples:
* http://thelounge.github.io/docs/getting_started/install.html
* https://dribbble.com/shots/1508716-Course-Player

**Comment by ffoodd** [comment]
Do not style links at all, except in main navigation. Should look good.

**Comment by ffoodd** [comment]
I tried to get some help to improve accessibility of Hologram output, in [Hologram's issue #133](https://github.com/trulia/hologram/issues/133). Would be great.

**Comment by ffoodd** [comment]
Currently working on [alix](https://github.com/ffoodd/alix). See you soon :)

**Comment by ffoodd** [comment]
Closed with last commit :)
