### ISSUE TITLE
Multiple dd tags should be allowed

### ISSUE THREAD

**Issue by bartveneman** [ffoodd/a11y.css#137]
Using multiple `dd` tags after a `td` currently throws a warning. According to the [W3C docs](http://www.w3.org/TR/html5/grouping-content.html#the-dd-element) this is perfectly fine, they even mention it as an example.

**Comment by ffoodd** [comment]
Indeed, thansk for reporting!

The issue is the selector `:not(dt) + dd` which restricts `<dd>` to directly follow a `<dt>`. This is wrong, I will adjust it to `:not(dt):not(dd) + dd` and it should be better!
