### ISSUE TITLE
selecteur css dans la documentation

### ISSUE THREAD

**Issue by goetsu** [ffoodd/a11y.css#140]
Il serait pratique d'afficher le selecteur css utilisé directement dans la documentation exemple ici : http://ffoodd.github.io/a11y.css/errors.html#empty-link 
Cela permettrait de :
- voir si il y a pas moyen de l'améliorer sans chercher directement dans les fichiers css
- de le réutiliser ailleurs
- de facilement y faire référence dans les issues

**Comment by ffoodd** [comment]
En effet, excellente idée ! Je vais intégrer ça dès que possible :) Merci Aurélien !
Je traduis le message en anglais pour nos lecteurs anglophones.

For english readers, this is the issue:
It would be handy to show the CSS selector in its associated documentation, like [this one](http://ffoodd.github.io/a11y.css/errors.html#empty-link ). It would allow:
- to see if it can be improved, without having to digg on scss files;
- to reuse it elsewhere;
- to easily quote it when opening an issue.
