### ISSUE TITLE
Fieldset should not have to be direct descendant of form

### ISSUE THREAD

**Issue by bartveneman** [ffoodd/a11y.css#142]
Currently a `fieldset` element that is not a direct descendant of a `form` is reported as a warning for illegal nesting. I can't find why a `fieldset` can't be nested in another element, so in my opnion it should be rewritten to `:not(form) fieldset` instead of `:not(form)>fieldset`.

**Comment by ffoodd** [comment]
I agree, and in fact it's also possible to nest fieldsets!

Thanks for the report!
