### ISSUE TITLE
erreur http://ffoodd.github.io/a11y.css/errors.html#empty-image-link

### ISSUE THREAD

**Issue by goetsu** [ffoodd/a11y.css#156]
alors déjà l'exemple donné ne fonctionne pas puisqu'il y a un <i></i> dans le lien cela ne match pas le sélecteur, l'erreur qui est déclenché c'est qu'il n'y a pas de alt sur l'image ce qui est déjà suffisant.

Par contre l'erreur qu'il faut vérifier c'est si y a un lien (sans title, aria-label, aria-labelledby ou avec title, aria-label, aria-labelledby vide) avec seulement une image dedans et que cette image a un attribut alt="" 

De plus, en l'état des tests RGAA3 cela ne serait toujours même pas forcement une erreur puisqu'il est possible d'utiliser le contexte du lien (p, du hx précédant, du li, du th associé ou de la phrase) pour fournir un intitulé. Mais là je pense que c'est clairement une erreur du RGAA3.

j'utiliserai donc plutôt le sélecteur : 
a:not([title]):not([aria-label]):not([aria-labelledby]) img:only-child[alt=""],
a[title=""] img:only-child[alt=""],
a[aria-label=""] img:only-child[alt=""],
a[aria-labelledby=""] img:only-child[alt=""]

Néanmoins cela ne déclenchera toujours pas d'alerte alors que ça devrait le cas si le lien est du type : 
```
<a href="/" title="">
    <img src="http://ffoodd.github.io/a11y.css/static/ffoodd.png" width="144" height="144"alt=""/> <i></i>
</a>
```
et déclenchera une alerte alors que ça devrait pas si du type : 
```
<a href="/" title="">
    <img src="http://ffoodd.github.io/a11y.css/static/ffoodd.png" width="144" height="144"alt=""/> dgdfgdfgdf
</a>
```
 mais je ne vois pas comment corriger ça

**Comment by ffoodd** [comment]
Après relecture, je crains malheureusement qu’il n’y ait rien de mieux à faire que supprimer ce test. Je m’explique : 
* il n’a de sens que si l’image est effectivement le seul enfant du lien ;
* or les images ne peuvent contenir de pseudo-élément, la stratégie d’a11y.css étant de tenter d’assigner le pseudo-élément porteur du message à un élément voisin ;
* or l’image n’a pas de voisin, puisque c’est le seul enfant… 

Impossible de faire fonctionner ce test en CSS :/
