### ISSUE TITLE
:empty, :blank, :-moz-only-whitespace

### ISSUE THREAD

**Issue by goetsu** [ffoodd/a11y.css#157]
devrait être à minima : 
a:empty:not([title]):not([aria-label]):not([aria-labelledby]),
a:empty[title=""], a:empty[aria-label=""], a:empty[aria-labelledby=""]

Cela dit ça ne sélectionnera pas qqchose comme : 
```
<a href="xxx"> </a>
```
(avec un espace dans le lien)

**Comment by ffoodd** [comment]
Pour le coup de l’espace, une nouvelle pseudo-classe ferait l’affaire (:blank) mais je dois trouver un moyen de l’isoler car non reconnue par les navigateurs actuels, elle invalide la totalité de mes sélecteurs…

Au-delà de cette perspective, on touche malheureusement la limite des CSS.

**Comment by goetsu** [comment]
en attendant :blank et uniquement pour FF y a :-moz-only-whitespace qui devrait être utilisable

**Comment by ffoodd** [comment]
Je relance cette question car il y a effectivement des solutions, je dois juste trouver un moyen d'isoler le sélecteur afin qu'il n'invalide pas les autres.

Ça devrait être marrent :)

**Comment by ffoodd** [comment]
*Note*
Pour la partie Sass, je pense générer un placeholder par navigateur cible [comme ça](http://sassmeister.com/gist/630fdd4eb7ceeabd6ed0). Ainsi les piles de sélecteurs incompatibles entre eux seront isolés.

Reste à décider si j'inclus au système existant ou si je le fais à part.
