### ISSUE TITLE
erreur http://ffoodd.github.io/a11y.css/errors.html#no-href

### ISSUE THREAD

**Issue by goetsu** [ffoodd/a11y.css#158]
à revoir car cela invaliderai aussi les cibles des ancres type 
```
<a name="toto"></a> 
```
ou 
```
<a id="toto"></a>
```
plus ne couvre pas cas

**Comment by ffoodd** [comment]
J’utilise désormais un sélecteur plus complexe : 
```
a[name=""][id=""][href=""],
a:not([name])[id=""][href=""],
a[name=""]:not([id])[href=""],
a:not([name])[id=""]:not([href]),
a[name=""]:not([id]):not([href]),
a:not([name]):not([id])[href=""],
a:not([name]):not([id]):not([href])
```

En excluant mutuellement les attributs vides ou absents.

Ça affine la gestion des ancres. Le sélecteur devient improbable et c’est tant mieux !

Un avis sur ce correctif ?
