### ISSUE TITLE
Why not run `npm publish`?

### ISSUE THREAD

**Issue by morishitter** [ffoodd/a11y.css#165]
I want to install ally.css from not only bower but also npm.

**Comment by ffoodd** [comment]
Honestly I don't use npm, that's the only reason. I will give it a try, and publish a11y.css - probably in June.

I found [a little doc](https://gist.github.com/coolaj86/1318304) to follow.

**Comment by ffoodd** [comment]
Better (and official) doc to follow: https://docs.npmjs.com/getting-started/publishing-npm-packages

**Comment by morishitter** [comment]
:+1:
