### ISSUE TITLE
Add z-index to the counter box

### ISSUE THREAD

**Issue by GaetanBt** [ffoodd/a11y.css#168]
Why not assign the maximum z-index possible to the counter box ?

I'm in the case where it goes behind some admin controls and it makes it impossible to read properly.

**Comment by Heydon** [comment]
+1

**Comment by GaetanBt** [comment]
BTW I already created an issue few months ago that you fixed.
Don't know what happened in the meantime :)

https://github.com/ffoodd/a11y.css/issues/11

**Comment by ffoodd** [comment]
It happened in [this commit](https://github.com/ffoodd/a11y.css/commit/fe81971358c8065a7df4d233bebccdc17dca2ae5#diff-1c7b6b155caa306b8d9873aabaca4668) when we switched from a master a11y.scss file to a more complex build. This part moved to base.scss but I think that Hugo's fork wasn't up-to-date.

This will be ease to fix :)

**Comment by GaetanBt** [comment]
Alright then :)
