### ISSUE TITLE
Smart use cases for attr()

### ISSUE THREAD

**Issue by ffoodd** [ffoodd/a11y.css#175]
I see at least three clever use cases for `attr()` function in displayed messages:
* displaying the `[scope]` attribute value (either `col` or `row`);
* showing `[alt]` attribute value on `<img>` (considering [this image bookmarklet](http://pauljadam.com/bookmarklets/images.html) by [Paul J. Adams](https://twitter.com/pauljadam), for example);
* indicating bad `[href]` value for links.

Despite it's pretty easy in pure CSS, using it in messages' strings doesn't work - probably the sequence of `quote()` / `unquote()`. I didn't push my test very far, but maybe @HugoGiraudel would have a simple trick to allow `attr()`?

**Comment by ffoodd** [comment]
First of all, `attr()` function must be unquoted in the `content` property.

That means either:
* adding a third parameter to the `message` mixin to specify an attribute to display; thus we would test if this parameter is used and display it conditionnaly at the beginning or at the end of the `message` mixin. That's pretty weird because we would have to write messages in another way. We also could add a line jump with `\A` and display attribute content on a second line.
* trying to display `attr()` in the middle of a message seems almost impossible to me: that would need splitting the message in three parts, first and third should be quoted and second should remain unquoted for `attr()`.

I don't know what's best, or even if it's a good idea!

Comments are welcome.

**Comment by HugoGiraudel** [comment]
That's a tricky one. I'll figure something when I have time.

**Comment by HugoGiraudel** [comment]
Quick and dirty: http://sassmeister.com/gist/3e24a29ae48c7a61b12e.

**Comment by ffoodd** [comment]
That sounds good!
There's no urge since I can't work on it for a few weeks, but I'll try to get this working on a11y.css as soon as I get back :)

Thanks Hugo!
