### ISSUE TITLE
Bad link

### ISSUE THREAD

**Issue by a5e** [ffoodd/a11y.css#178]
http://www.w3.org/TR/html-alt-techniques/#m6

> This is no longer being developed as a separate specification, there is no content here. You can find the alt attribute guidelines in the HTML specification.

It may be the case for other links.

**Comment by ffoodd** [comment]
Indeed, the correct link will be http://www.w3.org/TR/html51/semantics.html#alt .
Thanks for the report, I need to test a lot of links now :D

**Comment by ffoodd** [comment]
This link will be useful for this particular case: http://www.w3.org/WAI/tutorials/images/decision-tree/

There may be other helpful resources right there. I'll have a look.
