### ISSUE TITLE
Empty elements in no-alt test-case

### ISSUE THREAD

**Issue by a5e** [ffoodd/a11y.css#186]
There are 2 empty elements `<i> </i>` in this test-case : https://ffoodd.github.io/a11y.css/errors.html#no-alt

Are they useful or is this just a mistake ?

**Comment by a5e** [comment]
Nevermind, it was for #86.

**Comment by ffoodd** [comment]
Indeed, I just needed to cheat a little in order to show the message. 

Thanks for your vigilance!
