### ISSUE TITLE
Improve Gulp workflow

### ISSUE THREAD

**Issue by ffoodd** [ffoodd/a11y.css#189]
In order to re-enable more tests in CodeClimate.

Improve CSS output with some help: [CSSLint](https://github.com/CSSLint/csslint) already used in CodeClimate, [gulp-csscomb](https://www.npmjs.com/package/gulp-csscomb), [gulp-cssbeautify](https://www.npmjs.com/package/gulp-cssbeautify) and [gulp-autoprefixer](https://www.npmjs.com/package/gulp-autoprefixer).

It could be much better!

**Comment by ffoodd** [comment]
CSSLint configuration right there: https://github.com/CSSLint/csslint/wiki/Command-line-interface

**Comment by ffoodd** [comment]
Currently stuck with a [gulp-csslint issue](https://github.com/lazd/gulp-csslint/issues/35), I'll see other interesting plugins before this one.

**Comment by ffoodd** [comment]
Would it be useful to make clean and readable CSS file, then a compressed one to serve as a bookmarklet?

Still wondering.

**Comment by a5e** [comment]
Clean and readable for debugging could be useful. Devtools already handle this but selectors are on 1 line which is not readable for long selectors. And it could be useful to see diffs in the clean file instead of the compressed one.
