### ISSUE TITLE
Add examples on README.md

### ISSUE THREAD

**Issue by ffoodd** [ffoodd/a11y.css#191]
Some functionnalities like quarantine or cancelling test would ne much more understandable if there were some examples with it.

Should I split the file? It's pretty long now.

**Comment by a5e** [comment]
Yep it came to a point where it is difficult to understand everything in this file.

Here is how I see it:
README.md : Introduction and common use case and a list for other .md files
CONTRIBUTING.md : technical infos and contributions guideline (like how to build the documentation and run hologram)
INDEPTH.md or SOMETHING.md : references and Edge cases and known issues

**Comment by ffoodd** [comment]
You're right. I think about CUSTOMIZE.md, as it's a big part of current README.md and is probably inaccurate for a lot of users.
