### ISSUE TITLE
Conseil ou Avertissement ?

### ISSUE THREAD

**Issue by vibby** [ffoodd/a11y.css#198]
Ce n’est pas très explicite ce qui est des conseils et des avertissements. Un rappel de la couleur pour chaque ligne dans le récapitulatif de bas de page serait bienvenue !

**Comment by ffoodd** [comment]
L'ensemble du bloc est généré _via_ un pseudo-élément, ça va donc être chaud patate. Je vais essayer en jouant avec `background`, d'une manière ou d'une autre ça devrait être jouable.

**Comment by vibby** [comment]
J’ai bricolé un background à cet effet :
Preview ici : http://dabblet.com/gist/5527b60d3035b7d27490

```
background: rgba(0, 0, 0, .8);
background: -moz-linear-gradient(top, #911 0%, #911 31%, Gold 32%, Gold 49%, RoyalBlue 50%, RoyalBlue 70%, OliveDrab 71%, OliveDrab 100%);
background: -webkit-linear-gradient(top, #911 0%,#911 31%,Gold 32%,Gold 49%,RoyalBlue 50%,RoyalBlue 70%,OliveDrab 71%,OliveDrab 100%);
background: linear-gradient(to bottom, #911 0%,#911 31%,Gold 32%,Gold 49%,RoyalBlue 50%,RoyalBlue 70%,OliveDrab 71%,OliveDrab 100%);
border: 5px solid #fff;
```
À appliquer ici https://github.com/ffoodd/a11y.css/blob/master/sass/base/_base.scss

Je te laisse le soin de récupérer les variables pour les couleurs, et aussi pour les adoucir un peu :)

**Comment by ffoodd** [comment]
Oh super, merci ! 
Je vais faire quelques essais avec ça dans ma prochaine passe sur le projet :)

**Comment by ffoodd** [comment]
Et hop, j'ai fait plus discret, en imitant une tiret cadratin pour introduire un élément de liste.

![capture d ecran 2016-03-17 a 15 54 13](https://cloud.githubusercontent.com/assets/2890570/13849997/8df259ae-ec58-11e5-8ffd-e17725f84791.png)
