### ISSUE TITLE
Add an option to manually load a11y.css on documentation?

### ISSUE THREAD

**Issue by ffoodd** [ffoodd/a11y.css#217]
Heavier pages are very slow, probably due to a11y.css being one of the worst CSS file ever:
— [Errors page](http://ffoodd.github.io/a11y.css/errors.html)
— [Warnings page](http://ffoodd.github.io/a11y.css/warnings.html)

The biggest slow down is the «recalcule styles» thing, which I think is due to a11y.css levelled file being loaded. I already splitted it to load the minimum amount of CSS, but it's still a lot of incredibly complex selectors…

Any help or comments welcome :)

**Comment by ffoodd** [comment]
Already tried [loadCSS](https://github.com/filamentgroup/loadCSS) to load a11y.css asynchronously, but it's worse since it forces a recalcule styles. Page seems fast then freezes a few milliseconds, which is very annoying…

**Comment by ffoodd** [comment]
`translateZ( 0 )` isn't a good idea since it creates a new stacking context for messages.
I removed it from messages.

**Comment by rik** [comment]
What do you feel is slow? Initial loading? Scrolling? Some other interaction?

**Comment by ffoodd** [comment]
Initial loading, but I'd say it's quite decent now. I don't know if trying to improve perfs would be over-engineering?

I'm thinking about toggling `a11y.css`: do not load it but let user activate it, with a button or something.

**Comment by rik** [comment]
I ran this in Chrome profiler. It seems to spend a lot of time computing the selector matching. 
<img width="1026" alt="chrome-profile" src="https://cloud.githubusercontent.com/assets/3653/14636336/260bf2c2-062b-11e6-8ce1-b56c3af75fd0.png">

In Firefox with the `Show Gecko Platform Data` option enabled, it's spending a lot of time in [nsStyleSet::FileRules](https://dxr.mozilla.org/mozilla-central/source/layout/style/nsStyleSet.cpp?from=filerules#1102)
<img width="1060" alt="firefox-profile" src="https://cloud.githubusercontent.com/assets/3653/14636375/5b3b3336-062b-11e6-9c9a-f59d59e8888f.png">

**Comment by rik** [comment]
From this, it seems there are too many selectors.

**Comment by ffoodd** [comment]
Indeed this isn't surprising, as a11y.css is made of very long and  generic selectors. I think there's nothing to do for this…

I'll rename this issue to consider not loading a11y.css, and instead add an option to load it manually. Not sure of this.

**Comment by rik** [comment]
It would be interesting to count how many selectors are in the CSS file. A little bit of CSSOM for this. And then, we should open a bug for browsers to see if there is a performance improvement they could make.

**Comment by ffoodd** [comment]
Interesting. I actually load only partial files on those pages (only warnings on warning page, eg) so it's not really representative of the whole project.

I can't find any working CSS selectors counter, but according to [a11y-en.css](https://github.com/ffoodd/a11y.css/blob/master/css/a11y-en.css) I'd say we have between 5500 and 5800 selectors. Some of them are really, really complex. And almost all of them target HTML elements selector and/or attributes selector. I think the worst is:
```
body *:empty:not([hidden]):not([aria-hidden]):not([src]):not(button):not(a):not(iframe):not(textarea):not(area):not(base):not(br):not(col):not(command):not(embed):not(hr):not(img):not(input):not(keygen):not(link):not(meta):not(param):not(source):not(track):not(wbr):not(title)
```

which is really bad and should never be used elsewhere 乁(๏ᴥ๏)ㄏ

**Comment by ffoodd** [comment]
Last moves on a11y.css' Sass structure helped a lot. Selectors aren't repeated anymore, causing browsers to apply them easier.

Is there still a point to this issue?

**Comment by rik** [comment]
Do you have a commit showing the improvements?

**Comment by ffoodd** [comment]
It's been a lot of commits :/ I don't know if there's a way to show a diff between current and a specified commit on GitHub? I can't find ><

The best I can show for now: [a single CSS file on the major commit to me](https://github.com/ffoodd/a11y.css/blob/9df24c436cdcced731549c63d67924c75554ae41/css/a11y-fr_advices-only.css).

You can see that each test repeats the whole declarations, including their content, color et all.

Before that, [this is what it looked like](https://github.com/ffoodd/a11y.css/blob/a374cb28b372faad7f50e6082c4ec9391aa218b6/css/a11y-en.css). Declarations were unique, thus selectors were duplicated (first occurrence for common styles, second occurrences for specific styles: level and message).

Right now from what I've been able to measure, on Chrome the "Recalculate styles" thing decrease from ~900ms to ~600ms.

I'm not able to be as precise as you were in your own tests, but from what I see it's really better.

**Comment by HugoGiraudel** [comment]
@rik: There you go https://github.com/ffoodd/a11y.css/compare/469bc0781a77448db7ceffd93c01a83aebf5e936...bf267a33bb4795fb5273f70b2be32e1ab2bdb66b.

**Comment by ffoodd** [comment]
I think there's no need anymore since I load single level files now.
