### ISSUE TITLE
Make sure docs.js is the right file

### ISSUE THREAD

**Issue by ffoodd** [ffoodd/a11y.css#230]
Currently when I use `npm run docs`, the Hologram JS file is replaced by the SassDoc's one.

So, I need to test a few things to be sure it works as intended. See [this commit on gh-pages](https://github.com/ffoodd/a11y.css/commit/5682c56b402f956b10bf1c554db5e55d455427ea).

**Comment by HugoGiraudel** [comment]
Ask me if you need anything.

**Comment by ffoodd** [comment]
I didn't try at all for the moment, I don't think this will be complicated. But thanks, I will if I it's too difficult for me :)
