### ISSUE TITLE
href atribute is not required on <a> tags

### ISSUE THREAD

**Issue by arkhi** [ffoodd/a11y.css#235]
At the moment, having an anchor without `href` will trigger an alert of type “error” in a11y.css.

The [current HTML specifications](https://www.w3.org/TR/html/links.html#links-created-by-a-and-area-elements) mention this:
> The `href` attribute on `<a>` and `<area>` elements is not required; when those elements do not have `href` attributes they do not create hyperlinks.

The absence of `href` can be useful to express a link (past or future), which doesn’t exist in the actual context. Two examples I can think of:

- navigations like menus or paginations: a link to the actual page is unnecessary, or confusing.
- dead links: the link once existed, not anymore.

```html
<ol class="pagination">
    <li><a class="active">1</a></li>
    <li><a href="/url-2">2</a></li>
    <li><a href="/url-3">3</a></li>
    <li><del><a>4</a></del></li>
    <li><a href="/url-5">5</a></li>
</ol>
```

**Comment by ffoodd** [comment]
You're right, I didn't know about that :)

This means at least that the test shouldn't be an error since HTML is valid. I'll try to test it a bit, to see if a link without `href` behaves as intended within browsers and ATs.

If it's widely supported, it wouldn't be a warning either and could simply be an advice preventing a forgotten target.

Thanks!

**Comment by arkhi** [comment]
Yeah, it’s clearly a good idea to mention it in the report, as sometimes, people just use the `<a>` tag to have the pointer, and stick a `#` or a `javascript:void()` in the `href`, instead of a `<button>` with proper ARIA role and a bit of CSS + JS. :)

Styling anchors can be even more fun if you start to think that not all `<a>` are actual links, and `a:link` starts to make sense too! ;)

**Comment by ffoodd** [comment]
Ok so reading the test again, this is what I'm doing:
* keeping an error for empty `href=""`, single space `href=" "` and slashed `href="/"`. If `href` **is present**, it should be linking to a page or an anchor;
* adding an advice for missing `href`, just in case.

Other subtleties such as missing `name` or `id` are now removed.

**Comment by arkhi** [comment]
Cool… I don’t understand the issue with `href="/"`. What’s the problem with linking to the root of the domain?

**Comment by ffoodd** [comment]
Indeed it was an old test (I did test other attributes for this value, and it stayed as it). I didn't think about removing it while working on this issue! It's done now, and the documentation is up to date :)

Thanks!
