### ISSUE TITLE
How to display messages on non hover-able devices?

### ISSUE THREAD

**Issue by ffoodd** [ffoodd/a11y.css#239]
@pauljadam has a good point.

My first idea is to display messages without interactions, as WAVE or tota11y's flags. 
This would need:
- [x] shorter messages;
- [x] another way to display messages: fixed at top isn't possible, this probably means adding `position: relative` to the tested element and switch message to `absolute` positioning;
- [ ] add a kind of breakpoint to switch: media query (usual or giving a try to [level 4's hover / any-hover query](https://drafts.csswg.org/mediaqueries-4/#hover)) or `.matchMedia` for example. 

We'll have side effects obviously, but it's only a testing tool.

However this would considerably increase the size of CSS files. What about going this way all along and not only for non hover-able devices?

It needs a plan :)

**Comment by HugoGiraudel** [comment]
Once you have defined your spec, feel free to ask. I’ll help you with the Sass layer.

**Comment by saitho** [comment]
I used a11y.css on all levels to check https://www.wikipedia.org/. I can't check the advise on the logo because the warning of the element wrapping the logo is getting in the way.
This issue might be the right place for that, wasn't sure though. ^^

**Comment by ffoodd** [comment]
Hi @saitho, everywhere is a good place :)

In fact this is not really a bug, since messages are displayed in pseudo-elements DOM order and imbrication. Also message's level also matters since warning are considered more important than advices.

But that's a really good case to explain why displaying messages another way is needed :) So I think this is the good issue to comment, thanks!

**Comment by ffoodd** [comment]
Closed in #249
