### ISSUE TITLE
Add Chinese translation

### ISSUE THREAD

**Issue by pd4d10** [ffoodd/a11y.css#257]
Awesome project, really helpful 👍

Could you accept a PR to add Chinese translation?

**Comment by ffoodd** [comment]
Of course! I'd be very happy!

You'll find [how to add a new language](https://github.com/ffoodd/a11y.css/wiki/Translate-a11y.css) in the wiki.

Is there anything to adjust in CSS to display Chinese messages, or would it just be translation files? I'd be pleased to help if you need.

Moreover I'm working on new tests — [candidates are listed in this projetc](https://github.com/ffoodd/a11y.css/projects/1) — and on `feature/candidate-tests` branch: if you plan to translate messages in Chinese, would you mind help again when those new tests will be merged? If not, I'll find a way, do not worry ;)

**Comment by pd4d10** [comment]
Willing to help. Just @ me then

**Comment by ffoodd** [comment]
Issue fixed with #258.

Thanks a lot @pd4d1; I'll probably ping you before merging new tests :)
