### ISSUE TITLE
label:not([for]) is perfectly reasonable (the no-for error is broken)

### ISSUE THREAD

**Issue by chris-morgan** [ffoodd/a11y.css#276]
From the [HTML spec](https://html.spec.whatwg.org/#the-label-element) (emphasis mine):

> The `label` element […] can be associated with a specific form control […] either using the `for` attribute, **or by putting the form control inside the label element itself**.

Example:

```html
<label><input type=checkbox name=foo> Foo</label>
```

Sadly, the selector needed for this—`label:not([for]):not(:has(button, input:not([type = "hidden"]), meter, output, progress, select, textarea))`—won’t work in any present browsers because no one supports `:has()` yet. ☹

Anyway, as it is, the [no-for error](https://ffoodd.github.io/a11y.css/errors.html#no-for) is unreasonable, and should be at the very least downgraded to warning or advice. (I acknowledge that it’s more common to use `for` than to put the control inside the label, otherwise I’d request removal.)

**Comment by ffoodd** [comment]
You're right. 

FWIW, I made it an error since even while putting inputs in label is sufficient, you still can (and to my opinion, should) use a  `[for]` attribute. But it's opinionated.

I agree that downgrading it to warning is probably the better: warnings are also meant to ensure user will check it (just as empty `[alt]`, that might be OK but should be double-checked).

I'll do it soon, thanks for opening issue :)

**Comment by samnabi** [comment]
What's the rationale for including a for attribute even when the input is nested?

**Comment by ffoodd** [comment]
Is there any good reason to not including it, except saving a few octets?

"Always use a `for` attribute on `label`" is healthier, simplier to learn and retain, and ensure avoiding its omission when the pattern changes (for any reason: someone else moves the input outside the label, or another project is starting, you're working with both seniors and juniors, whatever).

And FWIW, in the French RGAA in its last revision, a `label` without a `for` attribute is not accepted.
Source: [test 11.1.2 (in French)](http://references.modernisation.gouv.fr/rgaa-accessibilite/criteres.html#test-11-1-2).
Tranlsation: [test 11.1.2 (in English on Github)](https://github.com/DISIC/rgaa_referentiel_en/blob/44e2bee0c710e37ca49901b1e6b8fae9b553fd5d/criteria.html#L3981)

Also [WCAG 2.1's H44 explictily says labels must have a `for` attribute](https://www.w3.org/TR/WCAG-TECHS/H44.html). And as said in [WAI tutorail about labelling controls](https://www.w3.org/WAI/tutorials/forms/labels/):

> Generally, explicit labels are better supported by assistive technology.

Si in fact I don't see any reason not doing it. And it's a bit more than my humble opinnion :)

But as I said, it can be accepted in some cases so I'll move the test to the warnings level.

**Comment by ffoodd** [comment]
More about this:

- [WordPress Accessibility Team tested many way to markup forms](https://make.wordpress.org/accessibility/2017/01/16/testing-form-functionality-with-different-assistive-technology/) and explicit labelleing always works, while implicit labelleing failed for Dragon users;
- [old version of H44](https://t.co/v2jJnnjFtr) mentions why implicit labelling isn't accepted, but in this one only very (very) old browsers and Ats are mentionned.

Many conversations started on Twitter, we may have more to read soon. :)

**Comment by ffoodd** [comment]
Thanks for the precision, @patrickhlauke !
I didn't understand this; that explains why the WAI tutorial evokes implicit labelling.

However it doesn't tell me if implicit labelling still causes troubles to some users. I need to dig deeper :)
