### ISSUE TITLE
Disabled test help

### ISSUE THREAD

**Issue by Cedric-ruiu** [ffoodd/a11y.css#278]
Hi,

Need your help :)

I don't understand how to use disable-tests() mixin. 
My disabled test : `@include disable-tests('warning:style-attr', 'warning:empty-nodes');`
If I include it at the end of a11y-fr.scss, nothing happens (normal), and if I add it just after @import 'utils/all'; I get an error :
 
`Error: sass/utils/_mixins.scss
Error: argument `$map` of `map-get($map, $key)` must be a map
       Backtrace:
       	sass/utils/_mixins.scss:82, in function `map-get`
       	sass/utils/_mixins.scss:82, in mixin `item`
       	sass/utils/_mixins.scss:145, in mixin `advice`
       	sass/themes/_advice.scss:27
        on line 82 of sass/utils/_mixins.scss
        $is-disabled: index(map-get($disabled-tests, $theme), $key);`

Same error if I put directly the keys into the variable file like this :
`$disabled-tests: ('warning:style-attr', 'warning:empty-nodes');`

Doc is not clear (maybe just for me), how to call correctly this mixin?

Cédric R

**Comment by ffoodd** [comment]
Hi there,

This was an authentic bug, thank you for the report!
It seems that it didn't work for at least two years :/

The next commit will fix it, then you should be able to use `@include disable-test()`.
FWIW, I recommend to apply this mixin directly in `_all.scss`: this way every CSS file will ignore the tests you disabled. I'll update the wiki to mention it :)

**Comment by Cedric-ruiu** [comment]
Hi,

Thanks to confirm that, I did not dare to say it.

The use var `$ disabled-tests` in` _variables.scss` have make more sense for me ;)

Cédric R.

**Comment by ffoodd** [comment]
Indeed, would be simpler :)

I'll add an enhancement issue to make this, but for now the bug is fixed \o/
Thanks a lot!
