### ISSUE TITLE
WebExtension icons

### ISSUE THREAD

**Issue by notabene** [ffoodd/a11y.css#282]
Hellowwww,

Please provide icons for the extension, at needed sizes:

```javacript
  "browser_action": {
    "default_title": "a11y.css",
    "default_popup": "popup/index.html",
    "default_icon": {
      "19": "images/toolbar.png",
      "38": "images/toolbar@2x.png"
    }
  },

  "icons": {
      "16": "icon_16.png",
      "48": "icon_48.png",
      "128": "icon_128.png"
  }
```

* `"default_icon"` is for the extension button in the toolbar
* `"icons"` is for the extension description in several contexts (addons.mozilla.org, addon page in browser, etc.)

**Comment by ffoodd** [comment]
I guess the number for each icon is the desired size, as a square?

**Comment by notabene** [comment]
Yup.

**Comment by ffoodd** [comment]
[a11y-css.zip](https://github.com/ffoodd/a11y.css/files/1514388/a11y-css.zip)

Et voilà :)
There're SVG source files and PNG exports, named `a11y-css_{size}.png`. Is that ok?

FWIW, see #163 for icon's history and variants :)
