### ISSUE TITLE
Gulp zip and copy

### ISSUE THREAD

**Issue by notabene** [ffoodd/a11y.css#283]
* Zip to create XPI
* Copy to push updated CSS to `webextension` folder

**Comment by ffoodd** [comment]
Copy CSS is pretty easy, either using `cp` command in a NPM script (declared in `package.json`, just like docs' scripts) or using a wrapper like Gulp-copy, [as used in sseeeedd](https://github.com/ffoodd/sseeeedd/blob/71275289462c5039803c2ffea2cd351b33314a42/gulpfile.js#L222).

Packaging a ZIP file is pretty easy to. If I correctly read [MDN's post about publishing WebExtension](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Publishing_your_WebExtension) we do not need XPI, do we?

If so, just like the copy task, [sseeeedd already uses a `.zip` packaging task](https://github.com/ffoodd/sseeeedd/blob/71275289462c5039803c2ffea2cd351b33314a42/gulpfile.js#L232).

And as for `cp`, on Unix systems we could use `zip` command. I don't think this would work on Windows though. Something like
```cmd
"webext:package": "cp -r css/* webextension/css &&  cd webextension && zip -r -FS ../a11y-css-WebExt.zip *"
```
would do the job. Then simply use `npm run webext:package`.

If we have to ensure a Windows compatiblity, we'll simply use gulp-copy and gulp-zip :)

Does this seem OK to you?

**Comment by ffoodd** [comment]
This is done. We now have two ways to build webxtension archive:
* run `npm run webext`
* or `gulp webextension` (after running `npm install``to get gulp-zip).

FYI, there's more CSS files in `webextension/css`, in order to prepare for #292
Let me know if you have any issue with this :)

**Comment by notabene** [comment]
<3
