### ISSUE TITLE
Outline : background tasks on page load

### ISSUE THREAD

**Issue by notabene** [ffoodd/a11y.css#284]
What we have so far:

1. When the page loads, nothing happens.
2. When the popup appears (after click on the button), we test if an outline setting was stored; if it was, we run the `addOutline()` method (adds the CSS in the page).

I'm not happy with it as it is:

* **Either it should load any new page and not outline** but then we cannot rely on storage to have a semi-permanent state to refer to when we toggle the outline CSS on and off, and will have to resort to two buttons: one ON, one OFF
* **Or we take it into account on page load**, this can be done through `background` methods declared in the manifest.

Either way I need to write some background code:

* In the first case the background code gets rid of the storage setting for Outline;
* in the second case it resets the page, as it would do if we clicked on the button 'Outline focus'.

What do you think?
ping @ffoodd

**Comment by notabene** [comment]
PS: "background" means that the page will run any code pushed through this method when it loads.

**Comment by ffoodd** [comment]
I'm not sure to understand.

Do you suggest to show outline on any page load if the user had previously used this button without resetting it?

What's the point of storing focus' activation state? Wuldn't it be more appropriate to require a user action before forcing focus outline?

Or did I miss the point?

**Comment by notabene** [comment]
You understood correctly. I was exposing all possible components, and will resort to the first solution “background code gets rid of the storage setting for Outline”
