### ISSUE TITLE
Show languages used

### ISSUE THREAD

**Issue by notabene** [ffoodd/a11y.css#291]
Show languages used in the page:

* highlight each zone featuring a `lang` attribute
* make the attribute visible

**Comment by ffoodd** [comment]
The goal would be to display `lang` values?

If so, I was considering to also show `alt` and `href` for example, using CSS only (with a new level for a11y.css, which could be `display` or `check`or whatever).

What's your opinion?

**Comment by notabene** [comment]
It's exactly what my bookmarklet does at the moment:

```javascript
javascript:s%20=%20document.createElement(%22style%22);s.setAttribute%20(%22type%22,%20%22text/css%22);t%20=%20document.createTextNode%20(%22*[lang]%20{border:2px%20solid%20red;%20}%20*[lang]:before%20{%20content:attr(lang);background:red;color:white;font:12px%20bold%20'courier%20new';}%22);s.appendChild(t);h%20=%20document.getElementsByTagName(%22head%22)[0];h.appendChild(s);void(0);
```

I think alt etc is another matter entirely, as we want to list them and be able to check on them.

The bookmarklet I use for checking alts now is not very good as it isn't very useful when something is on top of the image (say a `a[href]` in front of the `img`). I think for the moment I'll do the lang attribut separately and I've just created #293 to discuss images separately.

**Comment by ffoodd** [comment]
Indeed, as a matter of fact pseudo-elements won't display on `<img>` (a11y.css tries to display messages on next siblings element, **if any**).

But `[href]` and `[lang]` are easier to display.

**Comment by notabene** [comment]
Oh, btw, `[href]` is already covered by Chris Pederick's Web developer: Information → Display link detail.

**Comment by notabene** [comment]
> notabene moved this from NeedsReview to Done in Web Extension V1 on 5 Dec 2017

… and did not close it. Silly me.
