### ISSUE TITLE
Remove bookmarklets

### ISSUE THREAD

**Issue by ffoodd** [ffoodd/a11y.css#294]
After merging `webextension`, the bookmarklet thing will be useless.

To totally remove it:
* [x] remove the form and scripts on documentation website;
* [x] ~~remove cumulative levels files: webextension will allow us to add or remove levels one by one;~~
* [x] ~~remove `set-minimum-level` thing from the Sass layer.~~

This is meant to simplify the Sass part, and reduce the number of files being generated on Sass compilation.

**Comment by GaetanBt** [comment]
I removed all scripts, styles and documentation related to the bookmarklet. I just left the useless (for now) `aside button` CSS rules in case we need it in the future. Maybe we could remove that too.

**Comment by ffoodd** [comment]
Yep, drop it please :)

**Comment by GaetanBt** [comment]
Done in 45c4ef7b7ac65a1568fd60e41d8e8f11fa38a6eb
