### ISSUE TITLE
Proper SVG pictograms

### ISSUE THREAD

**Issue by notabene** [ffoodd/a11y.css#299]
In https://github.com/ffoodd/a11y.css/commit/b62961fb1be02f6092bfd1317ac8c06200fbc7d3 I committed some very ugly SVG (full in all its inkscape/sodipodi meta glory), temporary and I'm sure @ffoodd will do very nice corrections for it. 😛 

(refs #293)

**Comment by DiemenDesign** [comment]
@notabene @ffoodd If it helps your more than welcome to use icons from my project LibreICONS (http://diemendesign.github.io/LibreICONS/), they are minified and ARIA ready. If there's icons needed, I'm more than happy to add them.

**Comment by ffoodd** [comment]
Thanks @DiemenDesign I'm impressed by the number of icons you propose!!

Right now and since we only have 3 icons I'm using colors and fonts as seen in a11y.css - but I'm keeping an eye on LibreICONS ;)
