### ISSUE TITLE
Provide a11ycss-[lang]_all.css

### ISSUE THREAD

**Issue by notabene** [ffoodd/a11y.css#302]
In gulp: copy `css/a11ycss-[lang].css` to `webextension/css/a11ycss-[lang]_all.css`

or something 😉

We need the `_all` suffix for simplicity of scripting in the extension.
and then: #292 😄

**Comment by ffoodd** [comment]
Done!

You are now able to get every required CSS files in `webextension/css`.
Simply run `gulp webextension:css` or `npm run webext:css`.
