### ISSUE TITLE
Cannot build translation based on wiki page

### ISSUE THREAD

**Issue by GeorgeGkas** [ffoodd/a11y.css#305]
I want to add a new translation in Greek, but I get compile error when I run `gulp sass` command. These are the steps I followed so far:

1. clone the repo
2. run `npm i` to install dependencies
3. install gulp globally by running `npm i -g gulp`
4. create `gr.json` file under `/locales` folder in the project root.
5. create `a11y-gr.scss` under `/sass` folder in the project root with the following content:
```
@charset 'UTF-8';

@import 'locales/gr';

@import 'utils/all';
@include set-minimum-level('advice');
@import 'base/base';
@import 'themes/all';
```
6. Run `gulp sass`

I cannot execute successfully the last step due to import errors. Bellow I provide the stack trace:

```
➜  a11y.css git:(master) ✗ gulp sass
[00:33:55] Using gulpfile ~/Documents/forks/a11y.css/gulpfile.js
[00:33:55] Starting 'sass'...
Error in plugin 'sass'
Message:
    sass/a11y-gr.scss
Error: File to import not found or unreadable: locales/gr
       Parent style sheet: /home/georgegkas/Documents/forks/a11y.css/sass/a11y-gr.scss
        on line 3 of sass/a11y-gr.scss
>> @import 'locales/gr';
   ^

{ Error: sass/a11y-gr.scss
Error: File to import not found or unreadable: locales/gr
       Parent style sheet: /home/georgegkas/Documents/forks/a11y.css/sass/a11y-gr.scss
        on line 3 of sass/a11y-gr.scss
>> @import 'locales/gr';
   ^

    at options.error (/home/georgegkas/Documents/forks/a11y.css/node_modules/node-sass/lib/index.js:286:26)
  status: 1,
  file: '/home/georgegkas/Documents/forks/a11y.css/sass/a11y-gr.scss',
  line: 3,
  column: 1,
  message: 'sass/a11y-gr.scss\nError: File to import not found or unreadable: locales/gr\n       Parent style sheet: /home/georgegkas/Documents/forks/a11y.css/sass/a11y-gr.scss\n        on line 3 of sass/a11y-gr.scss\n>> @import \'locales/gr\';\n   ^\n',
  formatted: 'Error: File to import not found or unreadable: locales/gr\n       Parent style sheet: /home/georgegkas/Documents/forks/a11y.css/sass/a11y-gr.scss\n        on line 3 of sass/a11y-gr.scss\n>> @import \'locales/gr\';\n   ^\n',
  messageFormatted: '\u001b[4msass/a11y-gr.scss\u001b[24m\nError: File to import not found or unreadable: locales/gr\n       Parent style sheet: /home/georgegkas/Documents/forks/a11y.css/sass/a11y-gr.scss\n        on line 3 of sass/a11y-gr.scss\n>> @import \'locales/gr\';\n   ^\n',
  messageOriginal: 'File to import not found or unreadable: locales/gr\nParent style sheet: /home/georgegkas/Documents/forks/a11y.css/sass/a11y-gr.scss',
  relativePath: 'sass/a11y-gr.scss',
  name: 'Error',
  stack: 'Error: sass/a11y-gr.scss\nError: File to import not found or unreadable: locales/gr\n       Parent style sheet: /home/georgegkas/Documents/forks/a11y.css/sass/a11y-gr.scss\n        on line 3 of sass/a11y-gr.scss\n>> @import \'locales/gr\';\n   ^\n\n    at options.error (/home/georgegkas/Documents/forks/a11y.css/node_modules/node-sass/lib/index.js:286:26)',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-sass' }
[00:33:58] Finished 'sass' after 3.75 s
```

I followed exactly the steps as described in the [wiki page](https://github.com/ffoodd/a11y.css/wiki/Translate-a11y.css).

**Update**
I fixed the problem adding the following steps:

7. copy `/locales/gr.json` to `/sass/locales/_gr.scss`
8. Added `gr` locale to `/tasks/options.js` like so:

```
locales: ['en','fr','ru','zh','pt-br', 'gr']
```

Unfortunately I still do not know if this is just a hacky way or I missed anything. Do we have to update the wiki page?

**Comment by ffoodd** [comment]
Hi!

Indeed, this import changed quite recently and I messed up the wiki update :/
I'm sorry for this; your fix is the current way so you're good to go now.

I update the wiki page, thanks a lot for the report!

**Comment by ffoodd** [comment]
Ooops I'm back: in fact you should follow the wiki but run `gulp translate` once yopu've created your json file.

I'm updating the wiki page to describe this.

**Comment by ffoodd** [comment]
Done for [the wiki page about translating a11y.css](https://github.com/ffoodd/a11y.css/wiki/Translate-a11y.css): I hope it'll help!

**Comment by ffoodd** [comment]
@GeorgeGkas Please let me know if you still encounter any issue :)

**Comment by GeorgeGkas** [comment]
@ffoodd Thanks for the support. I indeed have another question. What files do you expect us to pull request when we add a new translation? Only the `json` file under `/locales/<lang>.json` or do we have to upload the compiled `css` files as well after running `gulp translate` and `gulp sass` commands? Can you update the wiki to include that information as well?

**Comment by ffoodd** [comment]
Good question indeed. Since PR will be merged directly on master, I recommend you run `gulp translate` to make your translation available to anyone without my intervention.

I'll update the wiki page :)

**Comment by GeorgeGkas** [comment]
Do I have to run `gulp sass` as well?

**Comment by ffoodd** [comment]
Yes, please :)

Here is the updated page about [adding a translation](https://github.com/ffoodd/a11y.css/wiki/Translate-a11y.css), in whic I try to better sum up what's needed for a complete pull request.

Doest this seem clearer to you?

**Comment by GeorgeGkas** [comment]
@ffoodd excellent work, thank you very much!

**Comment by ffoodd** [comment]
Thanks for your help and your patience, I trully appreciate it!

**Comment by GeorgeGkas** [comment]
Under `/sass/` I also see the following files:

- `*_advices-only.scss`
- `*_errors-only.scss`
- `*_obsolutes-only.scss`
- `*_warnings-only.scss`

Do we have to create those files as well or there is a `gulp` task that cares the job for us?

**Comment by ffoodd** [comment]
For now you don't have to create those files (and in fact, those files in FR, ZH, and PT-BR should be removed: I'll do it soon).

They're only used in the documentation website to avoid showing conflicting messages in test pages, and to speed up a bit the (very long) pages.
