### ISSUE TITLE
Move checkalts test page to Hologram

### ISSUE THREAD

**Issue by ffoodd** [ffoodd/a11y.css#308]
Should be pretty simple but needs to add a link in main navigation:
* in Hologram's header;
* in SassDoc theme.

And make sure to correctly handle assets in Hologram :)

**Comment by VioletVyxen** [comment]
There's is missing connection to hold the by enhancement into hologram. Remember hologram is  bigger than the average 8bit page. Hint: it's divisible by 8. I'll look into sass and get back to you on he opening page and if there Is a most justifying reason to expand then we can make it happen
