### ISSUE TITLE
RTL language without [dir]

### ISSUE THREAD

**Issue by ffoodd** [ffoodd/a11y.css#319]
Some languages, like arabic or hebrew, requires a text deicrection switch, as default text direction is left-to-right. See this [Accessibility Audit Tools test](https://alphagov.github.io/accessibility-tool-audit/test-cases.html#language-of-content-text-language-changed-without-required-change-in-direction).

There're lot more but the two main RTL languages are:
- Arabic: `ar`
- Hebrew: `he`

To check direction, I'd recommend to test:
```css
[lang="ar"]:not([dir="rtl"]),
[lang="he"]:not([dir="rtl"]) { … }

[lang="ar"] [lang]:not([dir="ltr"]),
[lang="he"] [lang]:not([dir="ltr"]) { … }
```

The 2nd selector would check any in-page language change in Arabic or Hebrew content.

Also need to check wrong match, as described in this [accessibility Tools Audit test](language-of-content-text-language-is-in-the-wrong-direction). Eg: `[dir="rtl"]:not([lang="ar"]):not([lang="he"])`.

Note: selectors could be simplified using `:matches()`, see #272 
```css
:matches([lang="ar"], [lang="he"]):not([dir="rtl"]) { … }
:matches([lang="ar"], [lang="he"]) [lang]:not([dir="ltr"]) { … }
```

For vertical writing-mode languages (such as Japanese, Korean or Chinese) we could show an advice asking to check wheter `writing-mode` is applied or not.

Any thought, anyone?

**Comment by ffoodd** [comment]
@notabene I'm assigning you for your opinion about this :)

**Comment by notabene** [comment]
No opinion, really. Good idea, basically.

**Comment by ffoodd** [comment]
Fixed in https://github.com/ffoodd/a11y.css/commit/793b1f2c7fa5a0b2ed8a48a79516884b0b3dec32
