### ISSUE TITLE
[webextension] Cross-browser compatibility

### ISSUE THREAD

**Issue by notabene** [ffoodd/a11y.css#321]
I'm incapable of porting the extension. This issue is a reminder to self to call out to the community.

**Comment by Wolf-Legend** [comment]
Application json key is not allowed in chrome but is mandatory for mozilla.
So we can just use same files with slight change in manifest.json file. 
Tried on chrome and working normally.

**Comment by Wolf-Legend** [comment]
Extension can be installed  in chrome after entering the author name but its not working in edge.
Nothing happens after clicking Apply.

**Comment by notabene** [comment]
Thanks a lot @Wolf-Legend - I'll look into this.

**Comment by Wolf-Legend** [comment]
This webpage can help a lot.
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json

**Comment by notabene** [comment]
@Wolf-Legend sorry for the long silence. I see you've committed a lot of stuff. Does this now work on Chrome, from your point of view? (I have no Chrome here).

**Comment by ffoodd** [comment]
@notabene Loading the webextension does work, FWIW the only feature not working (in Chromium / Ubuntu) is displaying images alternatives.

**Comment by ffoodd** [comment]
@notabene I made it fully working in Chromium by using [Mozilla's webextension-polyfill](https://github.com/mozilla/webextension-polyfill).

It's only a matter of look & feel from now on :+1:
