### ISSUE TITLE
Add a tool to check 1-4-12 criterion (WCAG 2.1)

### ISSUE THREAD

**Issue by PigeardSylvain** [ffoodd/a11y.css#325]
Is it possible to add a tool to test 1-4-12 criterion from WCAG 2.1
Here is a quick bookmarklet example (need to be validate) :

javascript:s%20=%20document.createElement(%22style%22)%3Bs.setAttribute(%22type%22%2C%22text%2Fcss%22)%3Bt%3Ddocument.createTextNode(%22*%20%7Bline-height%3A%201.5!important%3B%20letter-spacing%3A.12em!important%3B%20word-spacing%3A%20.16em%20!important%3B%7D%20p%7Bmargin-bottom%3A%202em!important%3B%20%7D%22)%3Bs.appendChild(t)%3Bh%20%3D%20document.getElementsByTagName(%22head%22)%5B0%5D%3Bh.appendChild(s)%3Bvoid(0)%3B

Thanks

**Comment by ffoodd** [comment]
Nice one, thanks :)

Before trying to implement this, here's [a Steve Faulkner's post on the topic](https://developer.paciellogroup.com/blog/2018/05/short-note-on-getting-spaced-out-with-sc-1-4-12-text-spacing/).

Definetely worh a try!

**Comment by notabene** [comment]
Refs: https://developer.paciellogroup.com/blog/2018/05/short-note-on-getting-spaced-out-with-sc-1-4-12-text-spacing/

**Comment by notabene** [comment]
Commited the Text spacing code.

It works for me.

@ffoodd please:

- [ ] test and confirm that we're OK
- [ ] add localization strings (I can't remember where you add them, apologies — too long off the project I guess)
- [ ] document for future developments where localization strings must be added
- [ ] package
