### ISSUE TITLE
@a11y-reset  do not remove void tag messages

### ISSUE THREAD

**Issue by ffoodd** [ffoodd/a11y.css#326]
For example, on [sseeeedd's elements page](https://ffoodd.github.io/sseeeedd/elements.html) the radio buttons' labels are still displaying error message, even if radio buttons do not trigger error anymore.

**Comment by Wolf-Legend** [comment]
The warning for inline styles on radio button label is only shown when the page is translated and not on the original page.

**Comment by ffoodd** [comment]
Already fixed by https://github.com/ffoodd/a11y.css/commit/198ca381a7c372fb15ea5aa27c775bd918a71181 (closed #316).

Only need to update webextension sources :)
