### ISSUE TITLE
<time> element and datetime attribute

### ISSUE THREAD

**Issue by lazarljubenovic** [ffoodd/a11y.css#336]
I'm getting an advice "Is date valid?" for the following:

```html
<time datetime="2018-11-30">2018-11-30</time>
```

![image](https://user-images.githubusercontent.com/7661457/48983247-a8382500-f0ec-11e8-8d22-5a4d233221a5.png)

Is there a reason for this? I know that an old HTML spec required a full ISO format, but partial timestamps should be fine now. Here's an example from the spec: https://www.w3.org/TR/html52/textlevel-semantics.html#example-f1d7cfdd.

**Comment by ffoodd** [comment]
Hi there,

As a matter of fact, advices are only meant to **advice**: those messages are triggered at some point, when criticity is low and there's no way to check precisely.

They don't target errors nor warnings, but aim to highlight some quality checks that might be ignored or unknown from the author.

In that case, `<time>` without a valid `datetime` attribute (and an understandable content, obviously) doesn't worth it, probably. This is explained (quite simply, I admit) in [the documentation website](http://ffoodd.github.io/a11y.css/advices.html#time).

Your example is just fine, but some author might not be aware of the `<time>` element requirements :)

This is why you can define a minimum level for a11y.css, to uncheck advices, obsoletes and so on…

Is that clearer , did I answer to your point?

**Comment by lazarljubenovic** [comment]
Yeah alright. Thanks for the explanation :heart:
