### ISSUE TITLE
[website] — improve accessibility

### ISSUE THREAD

**Issue by ffoodd** [ffoodd/a11y.css#359]
At least external links triggering a new tab should mention it.

And see if there're any other possible improvements.

**Comment by GaetanBt** [comment]
I'm beginning a list that I will complete progressively if I find any other ideas :

- [ ] external links triggering a new tab should mention it
- [ ] use `aria-current="page"` to mention the active page in the navigation bar

**Comment by GaetanBt** [comment]
Maybe consider running a small accessibility audit when we are ready to merge the Eleventy rewriting

**Comment by notabene** [comment]
I'm willing to help as an auditor.
