### ISSUE TITLE
Mention JetBrains' support somewhere

### ISSUE THREAD

**Issue by ffoodd** [ffoodd/a11y.css#369]
In the README.Md and / or on the website itself?

- [ ] [JetBrains' logo](https://www.jetbrains.com/company/brand/logos/)
- [ ] With `https://www.jetbrains.com/?from=a11y.css` as target.

**Comment by GaetanBt** [comment]
Are there any guidelines to follow from Jetbrains directly ?

**Comment by ffoodd** [comment]
From their mail:

>  If you feel that our tools have helped you a great deal, we would be grateful if you could mention JetBrains' support on your project's homepage. You could do this by placing our Logo and a link to JetBrains such as https://www.jetbrains.com/?from=ABC (make sure to replace ‘ABC’ with the name of your OS project, no spaces).

So I guess my two points checklist is fine :)

**Comment by GaetanBt** [comment]
Yep :+1:

**Comment by GaetanBt** [comment]
Done for the documentation's footer [here](https://github.com/ffoodd/a11y.css/pull/376/commits/9b2742827ef709aaf54df63c4be420d64d36cd29).

I'll let you do it in the README if you'd like to @ffoodd :smile:
