### ISSUE TITLE
Prepare documentation rewriting

### ISSUE THREAD

**Issue by GaetanBt** [ffoodd/a11y.css#377]
This is nothing more than a listing of all the things that would come to our minds and that need to be taking care of before merging #376 : 

@ffoodd feel free to add items :smile: 

- [ ] Clean input CSS (some prefixes or IE fixes may not be still useful)
  - [ ] use Autoprefixer for this! And… maybe for the whole project?
- [x] Update Node version to at least v12.10.0 in the Travis configuration
- [ ] Create a custom code demonstration block
- [ ] Revise themes markup (remove duplicated `<h1>`'s, use a list, etc)
- [ ] Improve the way to provide a content block without a Sass comment (see https://ffoodd.github.io/a11y.css/webextension.html)
- [x] Find a way to provide a dynamic `<title>` to data-generated pages
- [x] Use a Nunjucks component/macro to gather all "external link icons" in one place (=> finally we simply import a SVG file)
- [ ] Redirect old `.html` URL's to match the new ones without extensions
- [ ] Revise way to generate docs' CSS which seems to be a little buggy
- [ ] Remove all occurencies of "hologram" in code, comments, ...
- [ ] build site in `/docs` and deploy from here, then drop `gh-pages` banch and scripts

Unrelated but could be great:
- [ ] Drop SassDoc (?)

**Comment by ffoodd** [comment]
The To do will be easier to find in the PR itself :)
