### ISSUE TITLE
Labels wrapping their form element are incorrectly highlighted as errors

### ISSUE THREAD

**Issue by AshleyJSheridan** [ffoodd/a11y.css#388]
A label which wraps a form element is perfectly valid and accessible, but is being highlighted as an error by a11y.css.

The following code should be considered valid:

```
<label>
Name <input type="text name="name"/>
</label>
```

Currently, only form elements linked to their label by id or elements that use `aria-label` or `aria-labelledby` are considered valid.

**Comment by ffoodd** [comment]
In fact, it's only a warning — so it's meant to be double-checked, not considered as an error.

And [the implicit labelling is even mentionned as valid in the test's documentation](https://ffoodd.github.io/a11y.css/warnings.html#no-for).

Thanks for submitting an issue ☺️
