### ISSUE TITLE
Update links to RGAA criteries

### ISSUE THREAD

**Issue by zwiastunsw** [ffoodd/a11y.css#443]
The web addresses for the RGAA 3 criteries no longer exist. It is also not possible to refer to specific RGAA 4 criteria because the criteria headings on https://www.numerique.gouv.fr/publications/rgaa-accessibilite/methode-rgaa/criteres/#contenu do not have identifiers. Would it not be a good idea to update the addresses, using the page published by tanaguru https://rgaa.tanaguru.com/?

**Comment by ffoodd** [comment]
Nice spot, thanks! Criteria headings do have identifiers (eg. [1.1](https://references.modernisation.gouv.fr/publications/rgaa-accessibilite/methode-rgaa/criteres/#crit-1-1)) — however some criteria were abandoned while some appeared. 

I'm afraid there's quite a few checks to do before updating links—but will try!

**Comment by zwiastunsw** [comment]
Give me 2-3 weeks. I will prepare a pull request with changes. There is a bit of work to be done as the numbering of some criteria has also changed

**Comment by PhilippeVay** [comment]
A new site is in beta at this address: https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/  
It should've replaced the current RGAA 4.1 site a few weeks ago, I guess something else blocks the announcement?

`id`s have changed:
`#topic10` becomes `#10`  
`#crit-10-6` becomes `#10.6` (now with a dot)  
`#test-10-8-1` becomes `#10.8.1` (collapsed content becomes visible / deployed when needed 👍)  
There are also anchors for methodology sections like `fr-1.1.4` but it stays collapsed. Mmh it's an ARIA thing for the dropdown `button[aria-controls="fr-1.1.4"]`, probably not meant to be used with anchors.

IMHO it's better to wait a few weeks for the final URL (or switch URLs and ids now, then mass-replace the domain if it changes in a few weeks).

**Comment by ffoodd** [comment]
The new accessibilite.numerique.gouv.fr is now stable and the official RGAA website.

Moreover the RGAA 4.1.1 was released last week, so there might be other changes.

I'll tackle reamining links once I'm done with moving the webextension to manifest V3, if it's still hanging.

**Comment by zwiastunsw** [comment]
See: https://www.accede-web.com/notices/html-et-css/correspondance-rgaa-et-accede-web-html-et-css/
