### ISSUE TITLE
Check if anchor exists in targetted link

### ISSUE THREAD

**Issue by ffoodd** [ffoodd/a11y.css#467]
After #465, it's obvious Linkinator is not enough to ensure links aren't dead: it doesn't handle anchors.

Is there a way to check that an anchor exists in the target's DOM, or would it need a custom Node script to fetch content and check after that?

**Comment by PhilippeVay** [comment]
From feature request JustinBeckwith/linkinator/issues/79 => [commercetools/commercetools-docs-kit/issues/1185#issuecomment-1029917832](https://github.com/commercetools/commercetools-docs-kit/issues/1185#issuecomment-1029917832)
> Dart "[linkcheck](https://github.com/filiph/linkcheck)" (fast native binary, does have support for checking missing anchors, is [a github action](https://github.com/marketplace/actions/check-links-with-linkcheck), not as flexible as linkinator concerning rewriting staging URLs)

seems to be interesting. Though... - I've 0 experience with GitHub Actions - that could a problem:

> What is not supported by "linkcheck" is rewriting the hosts on our staging domain. This might be the blocker.

**Comment by ffoodd** [comment]
I'll have a look, thanks for the link!
