### ISSUE TITLE
Update WCAG links

### ISSUE THREAD

**Issue by ffoodd** [ffoodd/a11y.css#479]
[As stated by Eric Eggert on Mastodon](https://yatil.social/@yatil/112282900818571067), links to WCAG containing `/TR/` are outdated. There're plenty of them in a11y.css documentation, so need to update those!

**Comment by ThainBBdL** [comment]
It seems that the WCAG Techniques or Understanding links are all correct. (see https://github.com/ffoodd/a11y.css/blob/main/docs/advices.html#L338 ).
Links containing /TR/ mainly reference WCAG and WAI-ARIA specs.
But we might want to link to the latest spec version for WCAG and WAI-ARIA. 
WDYT?

**Comment by ffoodd** [comment]
Indeed, that's the spirit: ensure links are up-to-date :D
