### ISSUE TITLE
Test cases under consideration

### ISSUE THREAD

**Issue by ffoodd** [ffoodd/a11y.css#78]
Please feel free to argue those selectors, and to suggest any other test cases you could think of :)

Coming from DebugCSS:
- `nav:not([role])`
- `div[role="img"]:not([aria-label])`

Coming from REVENGE.CSS :
- `body > header:not([role="banner"])`
- `body > div > header:not([role="banner"])`
- `body > footer:not([role="contentinfo"])`
- `body > div > footer:not([role="contentinfo"])`
- `section [role="banner"]`
- `section [role="contentinfo"]`
- `article [role="banner"]`
- `article [role="contentinfo"]`
- `aside [role="banner"]`
- `aside [role="contentinfo"]`
- `#main:not(main):not([role="main"])`
- `#footer:not(footer):not([role="contentinfo"])`
- `#header:not(header):not([role="banner"])`
- `#banner:not(header):not([role="banner"])`

**Comment by ffoodd** [comment]
Thinking again about Revenge, we may add a new level targetting only bootstrap things.

**Comment by ffoodd** [comment]
Reading again [Opquast check-list](https://checklists.opquast.com/fr/accessibility-first-step/) we may find new tests to add.

**Comment by ffoodd** [comment]
From [diagnostic.css](https://github.com/karlgroves/diagnostic.css) by Karl Groves:
* [image role without aria-label](https://github.com/karlgroves/diagnostic.css/blob/master/diagnostic.css#L64);
* [dir attribute only accepts two possible values](https://github.com/karlgroves/diagnostic.css/blob/master/diagnostic.css#L113);
* [implicit headings](https://github.com/karlgroves/diagnostic.css/blob/master/diagnostic.css#L127);
* [accesskey](https://github.com/karlgroves/diagnostic.css/blob/master/diagnostic.css#L159);
* [empty th should be td](https://github.com/karlgroves/diagnostic.css/blob/master/diagnostic.css#L170);
* [nested table may be for layout](https://github.com/karlgroves/diagnostic.css/blob/master/diagnostic.css#L175).

I think all of those should be added to a11y.css :)

**Comment by ffoodd** [comment]
We may also test for checkboxes and radio buttons without [name] attribute, which is mandatory to group them.

**Comment by bartveneman** [comment]
A bit late to the party, but I think separating Bootstrap/Foundation/Whatever would be a nice addition, although keeping them in doesn't do any harm, AFAIK. Moving it to it's own scss file would make sense for me. 

Also not sure about the Revenge.css errors. They seem a bit opinionated. a11y.css is more trying to be helpful about things, in my opinion.

**Comment by ffoodd** [comment]
Hi @bartveneman,
indeed, errors from Revenge.css stayed "under consideration" because they're opinionated. 

Also please note that no test case are targeting Bootstrap/Foundation/Whatever for the moment, since I think it's pretty opinionated too. Also maintaining those tests would be a nightmare...

My last two comments are better candidates, I think. Do you agree?

**Comment by bartveneman** [comment]
LGTM

**Comment by ffoodd** [comment]
Adding some tests about respecting ARIA design patterns could be great, like:
* :not([role="tablist"]) [role="tab"] { ... }
I think about a fourth level for this. 
WIP :)

**Comment by GaetanBt** [comment]
Think it's a great idea !

**Comment by bartveneman** [comment]
Would they be warning or errors?

**Comment by ffoodd** [comment]
I was thinking about a new level, like "aria". But it's possible to qualify them on both errors, warnings and advices.

**Comment by ffoodd** [comment]
Just found a new source for ARIA tests: [display-wai-aria.css](https://github.com/masuP9/display-wai-aria.css). It only shows role and states without any comment or advice, but this is a good one :)

**Comment by ffoodd** [comment]
Note that we will be able to use this new structure for test cases:
```
selector { 
  message;
}

other selector {
  @extend %a11y-reset;
}
```

Should be fun :D

**Comment by ffoodd** [comment]
After #157 we're able to doissociate a test. That allows us to use non cross-browser selector.

Ex: 
* https://developer.mozilla.org/en-US/docs/Web/CSS/%3A-moz-broken
* https://developer.mozilla.org/en-US/docs/Web/CSS/-moz-force-broken-image-icon
* http://blogs.msdn.com/b/ie/archive/2008/09/08/microsoft-css-vendor-extensions.aspx
* https://developer.mozilla.org/en-US/docs/Web/CSS/Webkit_Extensions
* https://gist.github.com/webtobesocial/aefd6e25064c08e0cc9a
* https://developer.mozilla.org/en-US/search?q=%3A%3A-ms-&topic=css

**Comment by ffoodd** [comment]
Some CSS are used in [RGAA3 testing methodology](http://disic.github.io/rgaa_methodologie/#introduction). They could be somewhat handy, have to check :)

**Comment by ffoodd** [comment]
Recent commit on DebugCSS is very interesting, should have a look: https://github.com/imbrianj/debugCSS/commit/83297247b65661c7f0e330a0b615e1fed5e29f14

**Comment by ffoodd** [comment]
Another interesting source, lighter though: https://github.com/Darklg/CSSCommon/blob/master/css/debug.css

**Comment by ffoodd** [comment]
Also look at [DiagnosticCSS' last commit](https://gist.github.com/jhogue/6370800).

**Comment by ffoodd** [comment]
The [Visual ARIA bookmarklet](http://whatsock.com/training/matrices/visual-aria.htm) should be a great read for every ARIA related tests.

**Comment by ffoodd** [comment]
Please report to https://github.com/ffoodd/a11y.css/projects/1 for any idea :)
