### ISSUE TITLE
About bookmarklets

### ISSUE THREAD

**Issue by HugoGiraudel** [ffoodd/a11y.css#83]
Is there a clean way to a11y a bookmarklet? Perhaps with `rel="bookmarklet"` or something?

If there is, we should update the `a[href^="javascript:"]` rule to avoid dealing with bookmarklets.

**Comment by ffoodd** [comment]
After a few researches, I didn't find anything that could be used. Bookmarklets aren't anything natural on the web, not specified anywhere.

It think we shouldn't move anything for now.
