### ISSUE TITLE
"[width] and [height] attributes" test doesn't work

### ISSUE THREAD

**Issue by HugoGiraudel** [ffoodd/a11y.css#84]
[First test in Errors page](http://ffoodd.github.io/a11y.css/errors.html#dimensions): nothing happens when hovering the textarea.

Chrome Version 38.0.2125.122 Mac OS X Yosemite.

**Comment by ffoodd** [comment]
This one is either simple or complex: I'll close it but will open a new one. Explanations:
* textarea can only contain text, and thus can't contain psuedo-elements. I'll add it to edge cases;
* for this test case, I'll only move to a paragraph;
* I will change every textarea cases to use $self-closing;
* but there's a issue left: some tests (such as with and height attributes) may target void elements and that's not taken in consideration yet. I'll need a way to easily duplicate large cases (empty class or id, for example) that could match a void tag, maybe a kind of list continaining every void elements? (ISsue #115 created).
