### ISSUE TITLE
"Empty link" test is unpractical

### ISSUE THREAD

**Issue by HugoGiraudel** [ffoodd/a11y.css#87]
[This test](http://ffoodd.github.io/a11y.css/errors.html#empty-link): because the link is empty, the demo cannot be tested.

Chrome Version 38.0.2125.122 Mac OS X Yosemite.

**Comment by a5e** [comment]
We can apply this inline-style `display:inline-block;width:100px;height:20px` to it but that would not be nice to see it in the code example. Maybe apply it with javascript ?

**Comment by ffoodd** [comment]
I'm using two helpers from sseeeedd and a simple min-width based on an ID. That works fine for me, not a problem to have class or ID on examples.
