### ISSUE TITLE
"Namespaces" test description is incorrect

### ISSUE THREAD

**Issue by HugoGiraudel** [ffoodd/a11y.css#90]
[This test](http://ffoodd.github.io/a11y.css/errors.html#namespace)'s description says:

> Did you know that some characters should be avoided in class names and identifiers? Yep. Numbers and special chars.

This is plain wrong. Classes and IDs should not start by a digit, two hyphens or a hyphen followed by a digit. And special chars are allowed as long as they are escaped. There is nothing wrong with numbers and special chars in identifiers per se.

Chrome Version 38.0.2125.122 Mac OS X Yosemite.

**Comment by ffoodd** [comment]
Indeed other characters are allowed when allowed :)

Thanks for helping, I re-wrote this selector and test case!
