### ISSUE TITLE
"Invalid colgroup position" test is poorly written

### ISSUE THREAD

**Issue by HugoGiraudel** [ffoodd/a11y.css#98]
[This test](http://ffoodd.github.io/a11y.css/warnings.html#colgroup) doesn't actually introduce the warning. 

Chrome Version 38.0.2125.122 Mac OS X Yosemite.

**Comment by ffoodd** [comment]
Indeed, I saw the case. However test is correctly written, but most browsers do fix the DOM on tables.

I need to test further, but I may delete this one if all major browser fix this error by themselves.
